services:
  adsb-dashboard:
    build: ../03-data-consumption/dashboard
    container_name: adsb_dashboard
    ports:
      - "8501:8501"
    environment:
      MONGO_URI: ${MONGO_URI}
    restart: unless-stopped
