services:
  adsb-dashboard:
    build: ../03-data-consumption/dashboard
    container_name: adsb_dashboard
    ports:
      - "8501:8501"
    environment:
      - MONGO_URI=${MONGO_URI}
    restart: unless-stopped

  jupyter:
    build: ./jupyter
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ..:/workspace
    environment:
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
      - MONGO_URI=${MONGO_URI}
    restart: unless-stopped
