services:
  app:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: etl_app2
    env_file:
      - ../.env
    command: bash run_pipeline.sh
    volumes:
      - ../etl:/app
    restart: unless-stopped
