-- map1 — Silver "leanMVP" table (Supabase Postgres)
--
-- Authoritative DDL recovered from the Supabase project (it was originally
-- created directly in Supabase and never versioned). Captured here so the
-- Silver table is reproducible after a DROP. The loader in
-- ../etl/opensky_to_supabase.py writes into this table.
--
-- Note: append-only — the surrogate `id` is the only key, so the loader's
-- `ON CONFLICT DO NOTHING` never fires.

create table public.map1 (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  icao24 character varying null,
  time_position integer null,
  callsign character varying null,
  longitude real null,
  latitude real null,
  on_ground boolean null,
  true_track double precision null,
  vertical_rate double precision null,
  updated_at timestamp with time zone null,
  constraint map1_pkey primary key (id)
) TABLESPACE pg_default;
